name: Screenshot

on: [workflow_dispatch]

jobs:
  deploy:
    name: Screenshot & Post
    runs-on: ubuntu-latest

    steps:
      - name: Screenshot website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://findaclip.netlify.app/
          destination: website.png
