name: Screenshot

on: [workflow_dispatch]

jobs:
  deploy:
    name: Screenshot & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Screenshot website
        id: screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://charvey.live/
          destination: website.png
          delay: 2
      
      - name: Move image to screenshots folder
        run: |
          echo "Screenshot found: ${{ steps.screenshot.outputs.path }}"
          mkdir -p screenshots && mv ${{ steps.screenshot.outputs.path }} screenshots/website.png
      
      - name: Push new commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update website screenshot
