name: Screenshot

on: [workflow_dispatch]

jobs:
  deploy:
    name: Screenshot & Push
    runs-on: ubuntu-latest

    steps:
      - name: Screenshot website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://findaclip.netlify.app/
          destination: website.png

      - name: Push new commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update website screenshot
